import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import Header from "./_components/header";
import Footer from "./_components/Footer";
import { SupabaseSessionProvider } from "~/helpers/providers/Session";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SupabaseSessionProvider>
      <html lang="ar" dir="rtl">
        <body className={`font-sans ${inter.variable} overflow-y-scroll`}>
          <AntdRegistry>
            <Header />
            {children}
            <Footer />
          </AntdRegistry>
        </body>
      </html>
    </SupabaseSessionProvider>
  );
}
